# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{braincube}
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew MacLeod"]
  s.date = %q{2011-05-15}
  s.description = %q{A Rails Engine that provides basic CMS functionality.}
  s.email = %q{matt@matt-m.co.uk}
  s.extra_rdoc_files = [
    "README"
  ]
  s.homepage = %q{http://braincu.be}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Braincube CMS engine}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.4"])
      s.add_runtime_dependency(%q<haml>, ["= 3.0.25"])
      s.add_runtime_dependency(%q<fastercsv>, ["= 1.5.3"])
      s.add_runtime_dependency(%q<htmlentities>, ["= 4.2.2"])
      s.add_runtime_dependency(%q<zip>, ["= 2.0.2"])
      s.add_runtime_dependency(%q<chronic>, ["= 0.3.0"])
      s.add_runtime_dependency(%q<tickle>, ["= 0.1.7"])
      s.add_runtime_dependency(%q<sunspot_rails>, [">= 0"])
      s.add_runtime_dependency(%q<paper_trail>, ["= 2.0.1"])
      s.add_runtime_dependency(%q<will_paginate>, ["= 3.0.pre2"])
      s.add_runtime_dependency(%q<mime-types>, ["= 1.16"])
      s.add_runtime_dependency(%q<lapluviosilla-tickle>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_development_dependency(%q<mongrel>, [">= 0"])
      s.add_development_dependency(%q<cgi_multipart_eof_fix>, [">= 0"])
      s.add_development_dependency(%q<fastthread>, [">= 0"])
      s.add_development_dependency(%q<mongrel_experimental>, [">= 0"])
      s.add_development_dependency(%q<dr_dre>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<jammit>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.4"])
      s.add_dependency(%q<haml>, ["= 3.0.25"])
      s.add_dependency(%q<fastercsv>, ["= 1.5.3"])
      s.add_dependency(%q<htmlentities>, ["= 4.2.2"])
      s.add_dependency(%q<zip>, ["= 2.0.2"])
      s.add_dependency(%q<chronic>, ["= 0.3.0"])
      s.add_dependency(%q<tickle>, ["= 0.1.7"])
      s.add_dependency(%q<sunspot_rails>, [">= 0"])
      s.add_dependency(%q<paper_trail>, ["= 2.0.1"])
      s.add_dependency(%q<will_paginate>, ["= 3.0.pre2"])
      s.add_dependency(%q<mime-types>, ["= 1.16"])
      s.add_dependency(%q<lapluviosilla-tickle>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<mongrel>, [">= 0"])
      s.add_dependency(%q<cgi_multipart_eof_fix>, [">= 0"])
      s.add_dependency(%q<fastthread>, [">= 0"])
      s.add_dependency(%q<mongrel_experimental>, [">= 0"])
      s.add_dependency(%q<dr_dre>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<jammit>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.4"])
    s.add_dependency(%q<haml>, ["= 3.0.25"])
    s.add_dependency(%q<fastercsv>, ["= 1.5.3"])
    s.add_dependency(%q<htmlentities>, ["= 4.2.2"])
    s.add_dependency(%q<zip>, ["= 2.0.2"])
    s.add_dependency(%q<chronic>, ["= 0.3.0"])
    s.add_dependency(%q<tickle>, ["= 0.1.7"])
    s.add_dependency(%q<sunspot_rails>, [">= 0"])
    s.add_dependency(%q<paper_trail>, ["= 2.0.1"])
    s.add_dependency(%q<will_paginate>, ["= 3.0.pre2"])
    s.add_dependency(%q<mime-types>, ["= 1.16"])
    s.add_dependency(%q<lapluviosilla-tickle>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<mongrel>, [">= 0"])
    s.add_dependency(%q<cgi_multipart_eof_fix>, [">= 0"])
    s.add_dependency(%q<fastthread>, [">= 0"])
    s.add_dependency(%q<mongrel_experimental>, [">= 0"])
    s.add_dependency(%q<dr_dre>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<jammit>, [">= 0"])
  end
end

